#pragma once

#include <cstdint>

/// @file
/// @brief TRCIOR1レジスタのTRCGRD_CTRL。
enum class TRCIOR1_TRCGRD_CTRL : uint8_t {
  OUT_COMP_TRCIOB_DISABLED = 0,
  OUT_COMP_TRCIOB_LOW_LEVEL = 1,
  OUT_COMP_TRCIOB_HIGH_LEVEL = 2,
  OUT_COMP_TRCIOB_TOGGLE = 3,
  OUT_COMP_TRCIOD_DISABLED = 8, 
  OUT_COMP_TRCIOD_LOW_LEVEL = 9, 
  OUT_COMP_TRCIOD_HIGH_LEVEL = 10, 
  OUT_COMP_TRCIOD_TOGGLE = 11, 
  IN_CAPT_TRCIOD_RISING_EDGE = 12,
  IN_CAPT_TRCIOD_FALING_EDGE = 13,
  IN_CAPT_TRCIOD_BOTH_EDGE = 14,
};
